-- MySQL Script generated by MySQL Workbench
-- Tue Nov  3 16:17:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema outfit_shop_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `outfit_shop_db` ;

-- -----------------------------------------------------
-- Schema outfit_shop_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `outfit_shop_db` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema outfit_db
-- -----------------------------------------------------
USE `outfit_shop_db` ;

-- -----------------------------------------------------
-- Table `outfit_shop_db`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `outfit_shop_db`.`Product` ;

CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `description` TEXT(2000) NULL,
  `brand` VARCHAR(128) NULL,
  `image` VARCHAR(2083) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `outfit_shop_db`.`Category` ;

CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `parent_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parent_id_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `outfit_shop_db`.`Category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`Product_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `outfit_shop_db`.`Product_Category` ;

CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`Product_Category` (
  `product_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `fk_category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `outfit_shop_db`.`Product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_category_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `outfit_shop_db`.`Category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `outfit_shop_db`.`Review` ;

CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`Review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rate` TINYINT(6) UNSIGNED NULL,
  `filling` TEXT(2000) NOT NULL,
  `product_id` INT NOT NULL,
  `parent_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_parent_id_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_review_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `outfit_shop_db`.`Product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_review_parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `outfit_shop_db`.`Review` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `outfit_shop_db`.`Inventory` ;

CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`Inventory` (
  `product_id` INT NOT NULL,
  `size` VARCHAR(32) NOT NULL,
  `quantity` INT ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`product_id`, `size`),
  CONSTRAINT `fk_inventory_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `outfit_shop_db`.`Product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `outfit_shop_db`.`Address` ;

CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`Address` (
  `id` INT NOT NULL,
  `country` VARCHAR(64) NOT NULL,
  `city` VARCHAR(64) NOT NULL,
  `street` VARCHAR(64) NOT NULL,
  `num_house` INT NOT NULL,
  `num_flat` INT NULL,
  `postal_code` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `outfit_shop_db`.`Client` ;

CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`Client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(64) NOT NULL,
  `last_name` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `phone` TINYINT(20) NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_address_id_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `outfit_shop_db`.`Address` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `outfit_shop_db`.`Order` ;

CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`Order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `sum_price` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_id_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `outfit_shop_db`.`Client` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`Order_Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `outfit_shop_db`.`Order_Product` ;

CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`Order_Product` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_product_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `outfit_shop_db`.`Order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_product_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `outfit_shop_db`.`Product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`Product_Rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `outfit_shop_db`.`Product_Rating` ;

CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`Product_Rating` (
  `product_id` INT NOT NULL,
  `rating` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `fk_product_rating_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `outfit_shop_db`.`Product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`Sale_Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `outfit_shop_db`.`Sale_Event` ;

CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`Sale_Event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `sale_percent` TINYINT(100) UNSIGNED NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_sale_event_category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_sale_event_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `outfit_shop_db`.`Category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
