-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 10:38:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema outfit_shop_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `outfit_shop_db` ;

-- -----------------------------------------------------
-- Schema outfit_shop_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `outfit_shop_db` DEFAULT CHARACTER SET utf8 ;
USE `outfit_shop_db` ;

-- -----------------------------------------------------
-- Table `outfit_shop_db`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`address` (
  `id` INT NOT NULL,
  `country` VARCHAR(64) NOT NULL,
  `city` VARCHAR(64) NOT NULL,
  `street` VARCHAR(64) NOT NULL,
  `num_house` INT NOT NULL,
  `num_flat` INT NULL DEFAULT NULL,
  `postal_code` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `parent_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parent_id_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `outfit_shop_db`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(64) NOT NULL,
  `last_name` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_address_id_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `outfit_shop_db`.`address` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `brand` VARCHAR(128) NULL DEFAULT NULL,
  `image` VARCHAR(2083) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `size` VARCHAR(32) NOT NULL,
  `quantity` INT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_inventory_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `outfit_shop_db`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`ordering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`ordering` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `sum_price` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_id_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `outfit_shop_db`.`client` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`ordering_inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`ordering_inventory` (
  `ordering_id` INT NOT NULL,
  `inventory_id` INT NOT NULL,
  PRIMARY KEY (`ordering_id`, `inventory_id`),
  INDEX `fk_ordering_inventory_inventory_id_idx` (`inventory_id` ASC) VISIBLE,
  CONSTRAINT `fk_ordering_inventory_order_id`
    FOREIGN KEY (`ordering_id`)
    REFERENCES `outfit_shop_db`.`ordering` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ordering_inventory_inventory_id`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `outfit_shop_db`.`inventory` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`product_category` (
  `product_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `fk_category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `outfit_shop_db`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_category_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `outfit_shop_db`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`product_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`product_rating` (
  `product_id` INT NOT NULL,
  `rating` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `fk_product_rating_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `outfit_shop_db`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `client_name` VARCHAR(128) NULL DEFAULT 'Anonymous',
  `rate` TINYINT UNSIGNED NULL DEFAULT NULL,
  `filling` TEXT NOT NULL,
  `parent_id` INT NULL DEFAULT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_parent_id_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_review_parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `outfit_shop_db`.`review` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_review_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `outfit_shop_db`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`sale_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`sale_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `sale_percent` TINYINT UNSIGNED NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_sale_event_category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_sale_event_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `outfit_shop_db`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
