-- MySQL Script generated by MySQL Workbench
-- Wed Nov 18 13:42:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema outfit_shop_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `outfit_shop_db` ;

-- -----------------------------------------------------
-- Schema outfit_shop_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `outfit_shop_db` DEFAULT CHARACTER SET utf8 ;
USE `outfit_shop_db` ;

-- -----------------------------------------------------
-- Table `outfit_shop_db`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`address` (
  `id` INT NOT NULL,
  `country` VARCHAR(64) NOT NULL,
  `city` VARCHAR(64) NOT NULL,
  `street` VARCHAR(64) NOT NULL,
  `num_house` INT NOT NULL,
  `num_flat` INT NULL DEFAULT NULL,
  `postal_code` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `parent_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parent_id_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `outfit_shop_db`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(64) NOT NULL,
  `last_name` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_address_id_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `outfit_shop_db`.`address` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `brand` VARCHAR(128) NULL DEFAULT NULL,
  `image` VARCHAR(2083) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `size` VARCHAR(32) NOT NULL,
  `quantity` INT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_inventory_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `outfit_shop_db`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`ordering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`ordering` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `sum_price` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_id_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `outfit_shop_db`.`client` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`ordering_inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`ordering_inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ordering_id` INT NOT NULL,
  `inventory_id` INT NOT NULL,
  INDEX `fk_ordering_inventory_inventory_id_idx` (`inventory_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ordering_inventory_order_id`
    FOREIGN KEY (`ordering_id`)
    REFERENCES `outfit_shop_db`.`ordering` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ordering_inventory_inventory_id`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `outfit_shop_db`.`inventory` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`product_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  INDEX `fk_category_id_idx` (`category_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_category_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `outfit_shop_db`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_category_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `outfit_shop_db`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`product_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`product_rating` (
  `product_id` INT NOT NULL,
  `rating` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `fk_product_rating_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `outfit_shop_db`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `client_name` VARCHAR(128) NULL DEFAULT 'Anonymous',
  `rate` TINYINT UNSIGNED NULL DEFAULT NULL,
  `filling` TEXT NOT NULL,
  `parent_id` INT NULL DEFAULT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_parent_id_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_review_parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `outfit_shop_db`.`review` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_review_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `outfit_shop_db`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `outfit_shop_db`.`sale_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outfit_shop_db`.`sale_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `sale_percent` TINYINT UNSIGNED NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_sale_event_category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_sale_event_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `outfit_shop_db`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


USE outfit_shop_db;
	START TRANSACTION;

	INSERT INTO category(id, name) VALUES (1, 'All');
	INSERT INTO category(id, name, parent_id) VALUES (2, 'Men', 1), (3, 'Women', 1);
	INSERT INTO category(id, name, parent_id) VALUES (4, 'Hoodies', 2), (5, 'Hoodies', 3), (6, 'Pants', 2), (7, 'Pants', 3), (8, 'Socks', 2), (9, 'Socks', 3);

	INSERT INTO product(id, name, price, description, brand, image) VALUES (1, "Under Armour Men's Rival Fleece Logo Hoodie",
	'1273.90', "A classic active or casual look, this cozy fleece from Under Armour is updated with
	 moisture-wicking technology for comfort on the go.", "Under Armor", "https://slimages.macysassets.com/is/image/MCY/products/6/optimized/14653706_fpx.tif?op_sharpen=1&wid=1230&hei=1500&fit=fit,1&$filterxlrg$");
		 
	INSERT INTO product(id, name, price, description, brand, image) VALUES (2, "Under Armour Men's Tricot Jogger Pants",
	'890.20', "A classic active or casual look, these Under Armour bottoms will bring you comfort on the go.",
	"Under Armor", "https://slimages.macys.com/is/image/MCY/products/3/optimized/16330633_fpx.tif?op_sharpen=1&wid=1230&hei=1500&fit=fit,1&$filterxlrg$");
		 
	INSERT INTO product(id, name, price, description, brand, image) VALUES (3, "Under Armour Women's 6-Pk. Essential No-Show Socks",
	'616.13', "Stock up on comfort with this six pack of socks from Under Armour, in a no-show rise with stretch fabric.",
	"Under Armor", "https://slimages.macys.com/is/image/MCY/products/4/optimized/10189354_fpx.tif?op_sharpen=1&wid=1230&hei=1500&fit=fit,1&$filterxlrg$");
	 
	INSERT INTO product_category(id, product_id, category_id) VALUES (1, 1, 4), (2, 2, 6), (3, 3, 9);
	 
	INSERT INTO inventory(id, product_id, size, quantity) VALUES (1, 1, 'M', 24), (2, 1, 'L', 18), (3, 1, 'S', 6),
	(4, 2, 'XS', 3), (5, 2, 'M', 19), (6, 2, 'XL', 12), (7, 3, '34-36', 7), (8, 3, '36-38', 20), (9, 3, '38-40', 12);
	 
	INSERT INTO review(id, rate, filling, product_id, parent_id, client_name) VALUES(1, 4, 'Pretty cool pants, I liked it! But size is too small for me, so 4 stars.',
	2, NULL, 'Mike'), (2, 5, 'The quality of this hoodie is brilliant, color the same as on the website, a bit oversize. RECOMMEND!', 1, NULL, 'Tom');
	 
	INSERT INTO review(id, rate, filling, product_id, parent_id, client_name) VALUES (3, NULL, 'I think it is your fault that you bought pants with wrong size!', 2, 1, DEFAULT);
 
	INSERT INTO sale_event(id, start_time, end_time, sale_percent, category_id) VALUES (1, '2020.11.11 00:00:00', '2020.11.12 00:00:00', 37, 1),
    (2, '2020.11.12 00:01:00', '2020.11.30 23:59:00', 5, 1); 
    
    INSERT INTO address(id, country, city, street, num_house, num_flat, postal_code) VALUES
    (1, 'Ukraine', 'Kharkiv', 'Prospekt Nauky', 14, NULL, 61166),
    (2, 'Ukraine', 'Kyiv', 'Shevchenka', 23, 54, 85313);
    
    INSERT INTO client(id, first_name, last_name, email, phone, address_id) VALUES
    (1, 'Petro', 'Petrov', 'p.petrov@gmail.com', '380992384137', 1),
    (2, 'Vasily', 'Smirnov', 'v.sss121@gmail.com', '380664421740', 2);
    
    INSERT INTO ordering(id, client_id, sum_price) VALUES 
    (1, 1, 1273.90), (2, 2, 1506.33);
    
    INSERT INTO ordering_inventory(id, ordering_id, inventory_id) VALUES (1, 1, 1), (2, 2, 5), (3, 2, 9);
    
    COMMIT;
    


